services:
  scheduler:
    build: ./
    command: uvicorn scheduler.app:app --port 8000 --host 0.0.0.0
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      db: 
        condition: service_healthy
  spaceship:
    build: ./
    command: uvicorn spaceship.app:app --port 8001 --host 0.0.0.0
    volumes:
      - ./:/app
    ports:
      - 8001:8001
  worker:
    build: ./
    command: celery -A data_ingestor.tasks worker --concurrency=3 --loglevel=info
    # command: tail -f /dev/null
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
      - redis
  db:
    image: postgres:13.3
    hostname: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scheduler"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
  redis:
    image: redis:7.4.0-alpine
    hostname: redis
    ports:
      - "0.0.0.0:6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port for communication with workers
      - "0.0.0.0:15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
